import {
  AppSettings,
  CalculationInput,
  PresetItem,
  ToolItem,
} from '../types';

export const DEFAULT_TOOLS: ToolItem[] = [
  {
    id: 'tool-canva',
    name: 'Canva Pro',
    monthlyCost: 35,
    projectsPerMonth: 10,
    active: true,
  },
  {
    id: 'tool-adobe',
    name: 'Adobe Creative Cloud',
    monthlyCost: 145,
    projectsPerMonth: 12,
    active: false,
  },
  {
    id: 'tool-stock',
    name: 'Banco de Imagens (Freepik / Envato)',
    monthlyCost: 59.9,
    projectsPerMonth: 15,
    active: false,
  },
  {
    id: 'tool-plugins',
    name: 'Plugins & Mockups',
    monthlyCost: 29.9,
    projectsPerMonth: 10,
    active: false,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  financial: {
    defaultHourlyRate: 30,
    defaultTaxPercent: 6,
    defaultMarginPercent: 20,
    roundingMode: 'final_7',
  },
  complexityMultipliers: {
    simples: 1.0,
    media: 1.5,
    complexa: 2.0,
  },
  urgencyMultipliers: {
    normal: 1.0,
    urgente: 1.2,
    muito_urgente: 1.4,
  },
  pricingTiersMultipliers: {
    minimo: 0.9,
    recomendado: 1.0,
    premium: 1.25,
  },
  revisions: {
    includedRounds: 1,
    timePerRoundMinutes: 60,
    additionalModel: 'fixed',
    additionalFixedPrice: 35,
    additionalMinutes: 30,
  },
  recurringTools: DEFAULT_TOOLS,
  proposal: {
    professionalName: 'Seu Nome',
    companyName: 'Seu Estúdio de Design',
    whatsapp: '(11) 99999-9999',
    instagram: '@seuartstudio',
    paymentTerms: '50% de entrada no aceite e 50% na aprovação final (PIX ou cartão)',
    defaultDeadlineDays: 5,
    revisionPolicy: 'Alterações adicionais fora do escopo ou após aprovação são cobradas à parte.',
    defaultNotes: 'Proposta válida por 10 dias corridos a partir desta data.',
  },
};

export const INITIAL_INPUT: CalculationInput = {
  clientName: '',
  projectName: 'Pacote de Redes Sociais Completo',
  items: [
    {
      id: 'item-1',
      artType: 'feed_simples',
      quantity: 10,
      timePerArtMinutes: 30,
      complexity: 'simples',
      notes: 'Posts promocionais e institucionais',
      producedQuantity: 0,
      status: 'pendente',
    },
    {
      id: 'item-2',
      artType: 'story',
      quantity: 5,
      timePerArtMinutes: 20,
      complexity: 'simples',
      notes: 'Engajamento e avisos de novidades',
      producedQuantity: 0,
      status: 'pendente',
    },
    {
      id: 'item-3',
      artType: 'carrossel',
      quantity: 1,
      timePerArtMinutes: 60,
      complexity: 'media',
      notes: 'Carrossel educativo de 7 lâminas',
      producedQuantity: 0,
      status: 'pendente',
    },
  ],
  quantity: 16,
  artType: 'feed_simples',
  complexity: 'simples',
  timePerArtMinutes: 30,
  briefingMinutes: 30,
  communicationMinutes: 15,
  researchMinutes: 15,
  exportMinutes: 30,
  includedRevisionRounds: 1,
  revisionMinutesPerRound: 60, // 1 hora de alterações
  additionalRevisionModel: 'fixed',
  additionalRevisionPrice: 35,
  additionalRevisionMinutes: 30,
  hourlyRate: 30,
  directCosts: [],
  selectedToolIds: ['tool-canva'],
  taxRatePercent: 6,
  marginPercent: 20,
  urgency: 'normal',
  chosenTier: 'recomendado',
  deadlineDays: 5,
};

export const DEFAULT_PRESETS: PresetItem[] = [
  {
    id: 'preset-combo-social',
    name: 'Combo Redes Sociais Completo',
    description: '10 feeds simples, 5 stories e 1 carrossel estruturado.',
    items: [
      {
        id: 'p-1',
        artType: 'feed_simples',
        quantity: 10,
        timePerArtMinutes: 30,
        complexity: 'simples',
        notes: 'Feed institucional/vendas',
      },
      {
        id: 'p-2',
        artType: 'story',
        quantity: 5,
        timePerArtMinutes: 20,
        complexity: 'simples',
        notes: 'Stories dinâmicos',
      },
      {
        id: 'p-3',
        artType: 'carrossel',
        quantity: 1,
        timePerArtMinutes: 60,
        complexity: 'media',
        notes: 'Carrossel aprofundado',
      },
    ],
    briefingMinutes: 30,
    exportMinutes: 30,
    includedRevisionRounds: 1,
    isDefault: true,
  },
  {
    id: 'preset-10-posts',
    name: '10 Posts Simples',
    description: '10 artes para feed com tempo estimado de 30 minutos cada.',
    items: [
      {
        id: 'p-10',
        artType: 'feed_simples',
        quantity: 10,
        timePerArtMinutes: 30,
        complexity: 'simples',
      },
    ],
    briefingMinutes: 30,
    exportMinutes: 30,
    includedRevisionRounds: 1,
    isDefault: true,
  },
  {
    id: 'preset-10-stories',
    name: '10 Stories Rápidos',
    description: '10 stories com tempo ágil de 20 minutos por arte.',
    items: [
      {
        id: 'p-s10',
        artType: 'story',
        quantity: 10,
        timePerArtMinutes: 20,
        complexity: 'simples',
      },
    ],
    briefingMinutes: 20,
    exportMinutes: 20,
    includedRevisionRounds: 1,
    isDefault: true,
  },
  {
    id: 'preset-5-carrosseis',
    name: '5 Carrosséis Estruturados',
    description: '5 carrosséis mais aprofundados, 60 minutos por peça.',
    items: [
      {
        id: 'p-c5',
        artType: 'carrossel',
        quantity: 5,
        timePerArtMinutes: 60,
        complexity: 'media',
      },
    ],
    briefingMinutes: 45,
    exportMinutes: 30,
    includedRevisionRounds: 2,
    isDefault: true,
  },
  {
    id: 'preset-pacote-mensal',
    name: 'Pacote Mensal Completo (30 Artes)',
    description: '20 feeds simples, 8 stories e 2 carrosséis detalhados para o mês inteiro.',
    items: [
      {
        id: 'p-m1',
        artType: 'feed_simples',
        quantity: 20,
        timePerArtMinutes: 30,
        complexity: 'simples',
      },
      {
        id: 'p-m2',
        artType: 'story',
        quantity: 8,
        timePerArtMinutes: 20,
        complexity: 'simples',
      },
      {
        id: 'p-m3',
        artType: 'carrossel',
        quantity: 2,
        timePerArtMinutes: 60,
        complexity: 'media',
      },
    ],
    briefingMinutes: 60,
    exportMinutes: 45,
    includedRevisionRounds: 2,
    isDefault: true,
  },
];
